//@ sourceMappingURL=config.map
// Generated by CoffeeScript 1.6.1
var Config;

Config = (function() {

  function Config(rawConfig) {
    this.timeout = 60000;
    this.apiVersion = '1';
    this.mode = (rawConfig.mode)? '-' + rawConfig.mode : '';//will be used in url part
    this.newsstand = (rawConfig.newsstand)? rawConfig.newsstand : 'GBR';
    this.currency = (rawConfig.currency)? rawConfig.currency : 'GBP';
  }

  return Config;

})();

exports.Config = Config;
